dbpath: /home/e/ericy676/public_html/elections.db
open: true
admins:
  - ericy676
studentids: "/home/e/ericy676/csss/sids.txt"
privatekey: "/home/e/ericy676/csss/private.pem"
log: "/home/e/ericy676/public_html/elections.log"
email: csss@ubccsss.org
bios:
  - name: Ray Hua
    image: ../images/ray_hua.png
    desc: |
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus id bibendum nisi, a vestibulum lectus. Suspendisse blandit facilisis dolor, vel cursus diam lobortis a. Phasellus convallis pretium justo. Sed id scelerisque risus, ac porta mauris. Nam eu ultricies neque, eget ullamcorper magna. Vestibulum vehicula ultrices augue, in mollis risus cursus a. Quisque in gravida metus. Aenean laoreet viverra magna at suscipit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur felis sem, ultrices in scelerisque vel, rutrum in felis.
  - name: Jason Hsu
      image: ../images/jason_hsu.png
      desc: |
        Ello, I'm Jason. 3rd year CPSC. You might have seen me around in the ICICS or the Cube and if you've taken CPSC 121 in the past 2 years you've probably had me as a TA :) my first action if elected president will be to BAN TYPES, mandate that all coding be done solely with GITHUB COPILOT, and erect a temple in the ICICS to the GLORY OF NATURAL RECURSION. Jokes aside, I think it's sad how the CSSS has been stagnating in the past few years with COVID and other circumstances. For example, many internal processes and documents such as the constitution haven't even been reviewed since 2019 (did you know the constitution still refers to the President as "he"?). I'm running because I want to help the CSSS thrive again. I have too many ideas to put here, but if you have any questions or suggestions, definitely contact me at jsnhsu@(student dot ubc dot ca) or @Argonaut#1875 on discord!


positions:
  - name: President
    desc: |
      Responsibilities:

      * Chair all Executive meetings.
      * Prepare the agenda for each Executive meeting.
      * Supervise and direct the duties of the Executives.
      * Ensure that the position of Vice President, Finance is filled.
      * Liaise between the Department and the Club.
      * Ensure all duties of Executives are fulfilled.
      * Perform other duties as required.
      * Be responsible for the overall Club.
      * Act as chief spokesperson on behalf of the Club.

    candidates:
      - Ray Hua
      - Jason Hsu

  - name: Vice President, Volunteering
    desc: |
      Responsibilities:

      * Recruit undergraduate representatives to serve on Department committees.
      * Organize the recruitment of undergraduate students in the Department into other volunteer positions.

    # candidates:
    #   - 

  - name: Vice President, Internal
    desc: |
      Responsibilities:

      * Assist the President in carrying out his duties with respect to the day­to­day operations of the Club.
      * Assist the President in personnel issues related to the Club.
      * Manage, or appoint officer(s) to manage, the Club’s room(s) and inventories of merchandise and consumables.
      * Organize, or appoint an officer to organize, supply runs to restock Club inventories.
      * Chair executive meetings in the absence of the president.

    # candidates:
    #   - 

  - name: Vice President, External
    desc: |
      Responsibilities:

      * Liaise with companies and other entities outside the University via the relevant member of the Department.
      * Plan, supervise, and recruit assistance in executing the annual Career Fair.
      * Organize the acquisition of sponsored materials from companies for use as prizes and handouts to Members.
    # candidates:
    #   - 

  - name: Vice President, Social
    desc: |
      Responsibilities;

      * Be responsible for the planning, cost estimation, and execution of social and sporting events undertaken by the Club.

    # candidates:
    #   - 

  - name: Vice President, Communications
    desc: |
      Responsibilities:

      * Produce all advertising pertaining to Club business in all electronic and print media.
      * Communicate Club activities to the Members.

    # candidates:
    #   - 

  - name: Vice President, Finance
    desc: |
      Responsibilities:

      * Be responsible for the finances of the Club.
      * Prepare and submit all budgets required by the AMS and SUS.
      * Sign all requisitions of approved expenditures.
      * Obtain proposed expenditure estimates.
      * Be responsible for the purchase and sale of any of the Club’s merchandise.
      * Assist other officers in their interactions with the Alma Mater Society or any of its Commissions, if needed.

    # candidates:
    #   -

  - name: Vice President, Administration
    desc: |
      Responsibilities:

      * Take minutes at all General and Executive meetings; these minutes shall be published.
      * Organize meetings, when needed.
      * Direct communications between Executives, as required.

    # candidates:
    #   - 


  - name: Vice President, Academic
    desc: |
      Responsibilities:

      * Liaise between the department and student body on issues regarding academic matters requiring student input
      * Manage academic resources provided by the club, including the exam database and tutoring services
      * Direct academic-focused events undertaken by the Club

    # candidates:
    #   - 
