dbpath: /home/a/amyjzhu/public_html/dbfile.db
open: true
admins:
  - amyjzhu
  - s7p0b
studentids: "/home/a/amyjzhu/csss/sids.txt"
privatekey: "/home/a/amyjzhu/.ssh/private.pem"
log: "/home/a/amyjzhu/public_html/elections.log"
email: csss@ubccsss.org
bios:
  - name: Ray Hua
    image: https://i.imgur.com/EMMgK3v.jpg
    desc: |
      Hi there! I'm Ray, and I'm third year CS major running to be the VP-Finance of the CSSS. I've previously been the VP-Administration of the CSSS, and I'm ending a brief term as a Science AMS representative right now. The CSSS is a club focused on supporting CS students academically, career-wise, and socially, and as we move back into in-person learning, the CSSS needs to be able to bounce back to life. 
      The VP-F's role is to support the club financially in this regard, and I will strive to responsibly manage the CSSS's funds to support club initiatives and events. My experience with the AMS and SUS will also allow me to better navigate the bureaucracy of these organizations that club treasurers must deal with. A goal I would hopefully like to achieve, building off the work of two preceding VP-Fs who 
      have worked on this, is to organize and streamline the CSSS's internal financial workflow, and to better communicate our financial position to our members, recognizing that the latter depends on the former. Thanks for reading and voting!

  - name: Bernardine Lee Ho 
    image: https://i.imgur.com/9OkgDO7.jpg
    desc: |
      Who am I: My name is Bernardine Lee Ho, and I’m pursuing a second bachelor’s degree in Computer Science (BCS) at University of British Columbia. I have previously completed a Bachelor of Commerce at University of Toronto. Prior to joining BCS, I worked full-time in the Financial Services Industry for a couple of years. While completing my first degree, I was involved in a student advisory committee, 
      overseeing future plans within my faculty, and as a Marketing Coordinator for my university's e-Sports club. Why I am running for this position: I decided to run for VP Internal because I believe in the positive impact of student societies in enriching students’ university experience, and I want to contribute to the community as much as I can. Looking back to my experiences in my first undergrad, my 
      involvement in student clubs and societies in my first undergrad are where I learned some of the best lessons and met my dearest friends. I want to provide this opportunity for my fellow computer science students. What I hope to accomplish as VP Internal: My goal is to provide a space for computer science students where they can have enriching lessons outside of the classroom, meet new friends, and 
      make good memories. I understand the pressures that we all face as a computer science student, and my hope is that I can make your student life more pleasant by serving in the CSSS. How I will accomplish my goals: Having experience in both student societies and professional experience, I am confident that my experience will guide me to complete my duties effectively. I pledge to promote inclusivity 
      among our community online and offline (once campus opens), diligently assist in the day-to-day operations of the CSSS, actively engage in conversations with our students and act upon your opinions and suggestions to ensure your needs are being met.

  - name: Zackarya Hamza
    image: https://i.imgur.com/tS6WodD.jpg
    desc: |
      Hi! My name is Zack Hamza and I am running for the VP Social of CSSS. Currently, I am a 2nd-year student majoring in Computer Science. I am running for this position as I intend to be responsible for promoting the amazing events that the CSSS has planned for the upcoming year. I am incredibly passionate about computer science and I hope to encourage the computer science community at UBC to attend 
      our future events using our social media platform. I have past experience in promoting computer science events as I was the Social Media Lead of the CSCU (Computer Science Course Union) at UBC Okanagan, where I increased our following from 20 followers to around 230 followers today in a matter of a few months. I was also responsible for promoting BC Hacks 2.0, the CSCU's annual hackathon, where 
      160+ students attended. I hope you will consider voting for me as the VP Social for CSSS so I can bring the same level of success to this wonderful student society.

  - name: Yutong Li 
    image: https://ubccsss.org/files/ethan_yeung_2019.jpg
    desc: |
      I'm running for CSSS communications VP because I feel like the CSSS could have better exposure to the CS population with a better communications structure and a prettier looking website. As an executive I will: Redevelop some pages of the CSSS website to make it easier to navigate. Organize the internal structure so that we don't require as many executives for the organization.

  - name: Leonard Wang
    image: https://i.imgur.com/bx9muUy.jpg
    desc: |
      My name is Leonard, a 3rd-year Computer Science student currently interning at TD Capital Markets as a quantitative research analyst, and I will be joining Amazon in the summer of 2021 as a product manager for AWS in their Toronto office. I am very passionate about education and bridging the gap between technology and other disciplinary fields, and this passion is evidently reflected in what I do. 
      I was elected in 2020 as a national scholar as well as the youngest member to serve on the board of Computer Science Canada, along with two Nobel Prize Laureates to advance Canadian computing research, education, and innovation. During my term, I have organized several large student initiative programs such as the CS-Can Symposium and Canadian Undergraduate Computer Science Conference to educate 
      young leaders, and funded more than 20 advanced university research projects that have changed the world for the better. My objective is to provide more research opportunities for everyone and to guarantee an internship for all of our undergraduate students leveraging my connections and resources. I promise you to put all UBC students’ well-being above my own and to endeavour my very best to 
      create a better degree experience for everyone. I would be honoured and humbled to be part of the CSSS and I reassure you that you will not regret your decision for this leap of faith.

positions:
  - name: President
    desc: |
      Responsibilities:

      * Chair all Executive meetings.
      * Prepare the agenda for each Executive meeting.
      * Supervise and direct the duties of the Executives.
      * Ensure that the position of Vice President, Finance is filled.
      * Liaise between the Department and the Club.
      * Ensure all duties of Executives are fulfilled.
      * Perform other duties as required.
      * Be responsible for the overall Club.
      * Act as chief spokesperson on behalf of the Club.

    candidates:
      - Leonard Wang

  - name: Vice President, Volunteering
    desc: |
      Responsibilities:

      * Recruit undergraduate representatives to serve on Department committees.
      * Organize the recruitment of undergraduate students in the Department into other volunteer positions.

    # candidates:
    #   - 

  - name: Vice President, Internal
    desc: |
      Responsibilities:

      * Assist the President in carrying out his duties with respect to the day­to­day operations of the Club.
      * Assist the President in personnel issues related to the Club.
      * Manage, or appoint officer(s) to manage, the Club’s room(s) and inventories of merchandise and consumables.
      * Organize, or appoint an officer to organize, supply runs to restock Club inventories.
      * Chair executive meetings in the absence of the president.

    candidates:
      - Bernardine Lee Ho 

  - name: Vice President, External
    desc: |
      Responsibilities:

      * Liaise with companies and other entities outside the University via the relevant member of the Department.
      * Plan, supervise, and recruit assistance in executing the annual Career Fair.
      * Organize the acquisition of sponsored materials from companies for use as prizes and handouts to Members.
    # candidates:
    #   - 

  - name: Vice President, Social
    desc: |
      Responsibilities;

      * Be responsible for the planning, cost estimation, and execution of social and sporting events undertaken by the Club.

    candidates:
      - Zackarya Hamza

  - name: Vice President, Communications
    desc: |
      Responsibilities:

      * Produce all advertising pertaining to Club business in all electronic and print media.
      * Communicate Club activities to the Members.

    candidates:
      - Yutong Li

  - name: Vice President, Finance
    desc: |
      Responsibilities:

      * Be responsible for the finances of the Club.
      * Prepare and submit all budgets required by the AMS and SUS.
      * Sign all requisitions of approved expenditures.
      * Obtain proposed expenditure estimates.
      * Be responsible for the purchase and sale of any of the Club’s merchandise.
      * Assist other officers in their interactions with the Alma Mater Society or any of its Commissions, if needed.

    candidates:
      - Ray Hua

  - name: Vice President, Administration
    desc: |
      Responsibilities:

      * Take minutes at all General and Executive meetings; these minutes shall be published.
      * Organize meetings, when needed.
      * Direct communications between Executives, as required.

    # candidates:
    #   - 


  - name: Vice President, Academic
    desc: |
      Responsibilities:

      * Liaise between the department and student body on issues regarding academic matters requiring student input
      * Manage academic resources provided by the club, including the exam database and tutoring services
      * Direct academic-focused events undertaken by the Club

    # candidates:
    #   - 
