dbpath: /home/a/amyjzhu/public_html/dbfile.db
open: true
admins:
  - amyjzhu
  - s7p0b
studentids: "/home/a/amyjzhu/csss/sids.txt"
privatekey: "/home/a/amyjzhu/.ssh/private.pem"
log: "/home/a/amyjzhu/public_html/elections.log"
email: csss@ubccsss.org
bios:
  - name: Carmen Xu
    image: https://i.imgur.com/EMMgK3v.jpg
    desc: |
      Hello I’m Carmen (she/her) and I’m running to be VP Volunteering. I’m currently a Social Officer who has helped organize and plan events such as CSSS Presents a Stable Matching Problem, Midterm Care Packages, Meet the Professors Night, and CSSS Presents: Royal Flush. As well, I’m currently a CPSC TA and I hope to use the skills that I’ve learned to help with this position.
      I wanted to run for this position because I’m interested in having a greater role in the club.
      My 3 main goals as VP Volunteering are to:
      Encourage more students to help out with CSSS events, regardless of faculty.
      Hold monthly team-socials to help officers bond and promote team synergy.
      Work with other departments within the CSSS to help officers find the role that best fits them.
      I’ve made so many friends through this club, and joining the CSSS club has been one of the best decisions I’ve made at UBC. Thank you for reading my blurb and I hope to have your vote in this election!

  - name: Emily Gubski 
    image: https://i.imgur.com/9OkgDO7.jpg
    desc: |
      Hello everyone, my name is Emily and I am a third-year honors CPSC/MBIM student. I have spent 5 terms TAing the intro to computer science course and have spent 2 years working closely with faculty on course development. On top of that, I have also worked closely with the UBC CODE committee and have gotten to know many of the UBC CS faculty well.  
      I have also worked in the AMS for two years in the presidents and the VPadmin portfolio meaning that I have an understanding of the inner workings of the AMS. I have also worked as an RA in upper-year housing for 2 years now. All in all, I have spent my undergrad working with students and faculty in various capacities and I think that puts me in a position to be able to advocate for student needs.  
      My goal is to present CS student needs to the faculty and to act as a liaison to keep CS students in the loop about faculty decisions. A couple of things that I would like to look into are TA evaluation turn around times and faculty control over schedule/syllabus changes. 

  - name: Natalie Chen
    image: https://i.imgur.com/tS6WodD.jpg
    desc: |
      Hey guys!

      It has been a great year serving as your VP Academic from 2019 to 2020. I look forward to the opportunity of becoming your President for the year of 2020/2021!  
      If elected, I will continue to act as a front for the CS undergraduate society, making sure that student voices are both represented and heard at every table. From the smallest meetings among CSSS executives all the way to discussions with our department heads, you DESERVE to have your voices heard and recognized! Your executive team has accomplished so much in the past year with your help, and I hope to further our achievements in the next academic school year.  
      I believe that by combining our school’s academic prowess and our ability to work together we will produce great results. I care about your interests and your voice. I care about making sure your CS opportunities--both inside and outside the classroom--are as equally distributed and available to each and every one of you. Come share your ideas, and together we will make them happen.  
      Please feel free to contact me if you have any questions. I will answer them to the best of my ability.  
      --Natalie Chen
      <nataliechen1024@alumni.ubc.ca>

  - name: Ethan Yeung
    image: https://ubccsss.org/files/ethan_yeung_2019.jpg
    desc: |
      Over my previous term, the CSSS has made a number of improvements in the club space. We have free tea and coffee, we have a Switch, and we have an expanded variety of meals and snacks available. If I am re-elected, I hope to regularize the stocking and availability of items, with a particular focus on keeping perishables like ice cream available.  
      I’d like to think that the Cube is a nice place, and I’d like to keep it that way.

  - name: Ray Zhang
    image: https://i.imgur.com/bx9muUy.jpg
    desc: |
      Hi I'm Ray.  

      Other Ray.
      No, other other Ray.  

      I've served the CSSS as its VP Finance once before, though during personally troubled times I do not find myself to have fulfilled my duties to my own satisfaction. I want to fight for funding. I want to fight for grants. And I want to keep a system flowing so we aren't forced to remake the same mistakes, year after year as we roll over team after team without communication.
      This year I seek to serve the CSSS once more, and this year I hope to work more closely with not only my team, but my successors, and unite student societies aligned in adjacent fields. I hope you will grant me the opportunity to do so, as now as it was then, and may the tidings of tomorrow bring good health to you all.


  - name: Coco Wu
    image: https://i.imgur.com/H9YR4ZE.jpg
    desc: |
      ## Vote Coco for CSSS VP External  
      Hi! My name is Coco and I am running for VP External this year. I am currently in the second year, studying Computer Science and Statistics. I have been serving as an officer since the start of this term and I would love to do more for the CSSS. My main task will be to run the annual technical career fair. I am someone who takes initiatives and enjoys logistics; I will dedicate my time and efforts to assist the CSSS in serving all the students.



positions:
  - name: President
    desc: |
      Responsibilities:

      * Chair all Executive meetings.
      * Prepare the agenda for each Executive meeting.
      * Supervise and direct the duties of the Executives.
      * Ensure that the position of Vice President, Finance is filled.
      * Liaise between the Department and the Club.
      * Ensure all duties of Executives are fulfilled.
      * Perform other duties as required.
      * Be responsible for the overall Club.
      * Act as chief spokesperson on behalf of the Club.

    candidates:
      - Natalie Chen

  - name: Vice President, Volunteering
    desc: |
      Responsibilities:

      * Recruit undergraduate representatives to serve on Department committees.
      * Organize the recruitment of undergraduate students in the Department into other volunteer positions.

    candidates:
      - Carmen Xu

  - name: Vice President, Internal
    desc: |
      Responsibilities:

      * Assist the President in carrying out his duties with respect to the day­to­day operations of the Club.
      * Assist the President in personnel issues related to the Club.
      * Manage, or appoint officer(s) to manage, the Club’s room(s) and inventories of merchandise and consumables.
      * Organize, or appoint an officer to organize, supply runs to restock Club inventories.
      * Chair executive meetings in the absence of the president.

    candidates:
      - Ethan Yeung

  - name: Vice President, External
    desc: |
      Responsibilities:

      * Liaise with companies and other entities outside the University via the relevant member of the Department.
      * Plan, supervise, and recruit assistance in executing the annual Career Fair.
      * Organize the acquisition of sponsored materials from companies for use as prizes and handouts to Members.
    candidates:
      - Coco Wu

  - name: Vice President, Social
    desc: |
      Responsibilities;

      * Be responsible for the planning, cost estimation, and execution of social and sporting events undertaken by the Club.

    candidates:
      - 

  - name: Vice President, Communications
    desc: |
      Responsibilities:

      * Produce all advertising pertaining to Club business in all electronic and print media.
      * Communicate Club activities to the Members.

    candidates:
      - 

  - name: Vice President, Finance
    desc: |
      Responsibilities:

      * Be responsible for the finances of the Club.
      * Prepare and submit all budgets required by the AMS and SUS.
      * Sign all requisitions of approved expenditures.
      * Obtain proposed expenditure estimates.
      * Be responsible for the purchase and sale of any of the Club’s merchandise.
      * Assist other officers in their interactions with the Alma Mater Society or any of its Commissions, if needed.

    candidates:
      - Ray Zhang

  - name: Vice President, Administration
    desc: |
      Responsibilities:

      * Take minutes at all General and Executive meetings; these minutes shall be published.
      * Organize meetings, when needed.
      * Direct communications between Executives, as required.

    candidates:
      - 


  - name: Vice President, Academic
    desc: |
      Responsibilities:

      * Liaise between the department and student body on issues regarding academic matters requiring student input
      * Manage academic resources provided by the club, including the exam database and tutoring services
      * Direct academic-focused events undertaken by the Club

    candidates:
      - Emily Gubski
