dbpath: /home/q/q7w9a/elections.db
open: true
admins:
  - q7w9a
studentids: "/home/q/q7w9a/sids.txt"
privatekey: "/home/q/q7w9a/.ssh/id_rsa"
email: webmaster@ubccsss.org
bios:
  - name: Tristan Rice
    image: https://avatars1.githubusercontent.com/u/909104
    desc: |
      The current webmaster and elections officer.

      Yes, I am Tristan.
  - name: Megan
    desc: I will be a very good VPI, yes.
  - name: Jill
    image: https://i.pinimg.com/236x/de/4d/af/de4daf20b7e43fc4bca3450d86a1a32c--backpack-coding.jpg
    desc: |
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce quis
      tincidunt lorem. Suspendisse orci urna, tincidunt non porttitor et,
      euismod nec ipsum. Vestibulum ac sagittis nisl. Ut ut ipsum et libero
      ultrices laoreet in porttitor purus. Aliquam sodales porttitor augue, id
      mollis eros lacinia vitae. Aliquam rutrum orci sit amet bibendum sagittis.
      Vivamus eu malesuada est. Quisque eget sagittis arcu. Nullam egestas
      consectetur risus. Sed id cursus massa. Maecenas bibendum ornare aliquet.
      Interdum et malesuada fames ac ante ipsum primis in faucibus.

      Duis condimentum varius consequat. Nunc ut nibh id erat sagittis volutpat
      eget eu ante. Aliquam nec aliquam nibh. Proin vitae risus ac velit maximus
      dapibus nec at quam. Maecenas consectetur, urna eu tincidunt aliquam,
      risus tellus aliquet metus, in scelerisque massa nunc sit amet est.
      Curabitur mattis nec sem egestas maximus. Phasellus malesuada augue sit
      amet tellus interdum, at lobortis lorem imperdiet. Curabitur ornare quam
      mattis massa tincidunt volutpat. Sed aliquam nec ex ac vehicula. Donec
      lacus nisl, ornare vitae dolor id, vestibulum venenatis ex. Proin
      scelerisque arcu at diam sodales placerat. Donec aliquet ligula turpis,
      non semper ante fermentum vel. In tincidunt sodales enim condimentum
      porta.

      Fusce in dui vitae magna semper ultrices. Aenean commodo tortor at mi
      sagittis vehicula. Mauris facilisis felis non purus vehicula consectetur
      sed id ante. Maecenas dignissim ipsum lectus, ac condimentum tortor
      malesuada id. Suspendisse urna arcu, iaculis non dolor quis, lacinia
      viverra ante. In hac habitasse platea dictumst. Nunc venenatis nulla
      nulla, vitae facilisis neque ullamcorper in. Nam iaculis tellus vitae.



positions:
  - name: President
    desc: |
      Responsibilities:

      * Chair all Executive meetings.
      * Prepare the agenda for each Executive meeting.
      * Supervise and direct the duties of the Executives.
      * Ensure that the position of Vice President, Finance is filled.
      * Liaise between the Department and the Club.
      * Ensure all duties of Executives are fulfilled.
      * Perform other duties as required.
      * Be responsible for the overall Club.
      * Act as chief spokesperson on behalf of the Club.

    candidates:
      - Tristan Rice
      - Bob

  - name: Vice President, Volunteering
    desc: |
      Responsibilities:

      * Recruit undergraduate representatives to serve on Department committees.
      * Organize the recruitment of undergraduate students in the Department into other volunteer positions.

    candidates:
      - Bob

  - name: Vice President, Internal
    desc: |
      Responsibilities:

      * Assist the President in carrying out his duties with respect to the day­to­day operations of the Club.
      * Assist the President in personnel issues related to the Club.
      * Manage, or appoint officer(s) to manage, the Club’s room(s) and inventories of merchandise and consumables.
      * Organize, or appoint an officer to organize, supply runs to restock Club inventories.
      * Chair executive meetings in the absence of the president.

    candidates:
      - Jill
      - Jennifer
      - Megan

  - name: Vice President, External
    desc: |
      Responsibilities:

      * Liaise with companies and other entities outside the University via the relevant member of the Department.
      * Plan, supervise, and recruit assistance in executing the annual Career Fair.
      * Organize the acquisition of sponsored materials from companies for use as prizes and handouts to Members.

  - name: Vice President, Social
    desc: |
      Responsibilities;

      * Be responsible for the planning, cost estimation, and execution of social and sporting events undertaken by the Club.

    candidates:
      - Megan

  - name: Vice President, Communications
    desc: |
      Responsibilities:

      * Produce all advertising pertaining to Club business in all electronic and print media.
      * Communicate Club activities to the Members.

  - name: Vice President, Finance
    desc: |
      Responsibilities:

      * Be responsible for the finances of the Club.
      * Prepare and submit all budgets required by the AMS and SUS.
      * Sign all requisitions of approved expenditures.
      * Obtain proposed expenditure estimates.
      * Be responsible for the purchase and sale of any of the Club’s merchandise.
      * Assist other officers in their interactions with the Alma Mater Society or any of its Commissions, if needed.

  - name: Vice President, Administration
    desc: |
      Responsibilities:

      * Take minutes at all General and Executive meetings; these minutes shall be published.
      * Organize meetings, when needed.
      * Direct communications between Executives, as required.
